### ISSUE TITLE
Auto Zone Bug

### ISSUE THREAD

**Issue by dubcat** [JusKillmeQik/LevelingGuide#28]
Auto Zone goes back to the first time the zone was mentioned in the guide, and not to the next step.
Here is an example of the guide I made.

"act" : "Act I",
			"part" : "Part I",
			"list" : [
				"01 Twilight Strand",
				"02 Lioneye's Watch",
				"03 The Coast",
				"04 The Mud Flats",
				"05 The Submerged Passage",
				"06 The Coast",
				"07 The Tidal Island",
				"08 Lioneye's Watch",
				"09 The Submerged Passage",
				"10 The Ledge",
				"11 The Climb",
				"12 The Lower Prison",
				"13 The Upper Prison",
				"14 The Warden's Quarters",
				"15 Lioneye's Watch",
				"16 Prisoner's Gate",
				"17 The Ship Graveyard",
				"18 The Cavern of Wrath",
				"19 The Lioneye's Watch",
				"20 The Cavern of Wrath",
				"21 The Cavern of Anger"
			]

**Comment by JusKillmeQik** [comment]
Yeah, the numbers in front are the level of the zone, not the order they show up. The guide uses that number to calculate the experience you're receiving in that area. It only uses the name when looking for a text file, so that's why it always goes to the first one. I don't currently support having two notes for the same place. If that's a feature you want, I can look into it, but it would be hard for me to keep track of how many you had and if you were really visiting for the second time or if you just stepped back into town because you forgot something. I recommend just putting your notes for the area in the same text file and separate them like this:

Pick up these gems
Get this reward
...
Pick up those gems now
Get this other reward
