### ISSUE TITLE
Just Found Out This Tool Silently Deletes Client.txt - Please Rename it Instead

### ISSUE THREAD

**Issue by dsnvwlmnt** [JusKillmeQik/LevelingGuide#33]
While looking at the code I was very surprised to find out that it deletes the user's Client.txt outright, without ever asking or mentioning this. All this time I had no idea that my Client.txt was being flushed every run and long gone.

While this isn't a huge deal in the grand scheme of things, it bothers me that I can no longer dig through my Client.txt to find previous messages and whatnot. Especially since this behavior was never listed anywhere that I know of.

My suggestion is to rename the file (based on timestamp & date) instead of deleting. The user can then delete the file(s) at their leisure, similar to how the game normally works.

**Comment by JusKillmeQik** [comment]
I delete the client.txt file because GGG never uses it or rotates it based on timestamp and date. Mine had grown to almost a gig and took over 15 minutes to open! While I understand the attachment to the log and the desire to look back in it, I'm not going to take time this league to code in a rotating log that GGG should have done in the first place.

I left notes in the script on how to disable the deletion of the client.txt file if you would like to keep yours. However, over time, this will greatly slow down the script as it has to load that file every couple seconds to check for new entries.

You can also backup the file yourself by renaming it before launching my script. It only deletes on script launch, so if you leave the script running your file is safe.

I apologize for not listing that I delete the client.txt file more clearly, I did not think it would affect most people and I didn't want to scare people by announcing I delete a file. (I clearly state it in the code for anyone reading it, I just didn't announce it in the readme).

Perhaps in my next update I'll code something in that protects that file, but again, it will grow forever and take up space on your hard drive you don't even know about. Let me know if that's really something you want and I'll consider it.

**Comment by JusKillmeQik** [comment]
Instructions are in this commit: 2d337e40729746d4e827942192bd8fb892b0124e

I'll leave this open for a response from you.

**Comment by dsnvwlmnt** [comment]
I'm not personally affected (nor most people, I'm sure), but I was surprised when I found out. At the end of the day I don't really care that much. It's just a philosophical position I hold, that a program should never modify third party files without asking or notifying the user.

**Comment by JusKillmeQik** [comment]
I now only delete the file if it's over 10Mb, and I give a clear warning before doing it. I also allow the user to cancel if they want to keep the file.

Thanks again for pointing out issues.

**Comment by dsnvwlmnt** [comment]
Ohhh nice, thanks for that!
