### ISSUE TITLE
Application Focus-Stealing

### ISSUE THREAD

**Issue by dsnvwlmnt** [JusKillmeQik/LevelingGuide#8]
This macro is causing some kind of issue/interference when entering new zones.

1) If you quickly use a skill upon zoning in, often it won't register, like focus was temporarily stolen from the game.

2) If i'm alt-tabbed, it forces you back to PoE.

Neither of these things occurred with the previous version.

**Comment by JusKillmeQik** [comment]
They did actually occur with the previous version. You just didn't notice it because the zone changing wasn't automatic. It forces focus back to the game after you click manually on the drop down menu, because that menu isn't in PoE. And since it stays hidden when PoE isn't shown, it had to bring focus back to the game. Also, if I draw something (the overlay), that happens outside of PoE so that's where you lose the focus. I capture the mouse state and put it back so that if you're clicking you shouldn't notice, but I do not capture keyboard state. I could not find a way to generate the gui without taking focus from PoE. I am very open to suggestions. I tried to make the change happen as fast as possible, but no matter what it always takes just under a second for the automation to work, so most people will have taken an action by then.

I will continue to play with this, but I spent hours on it already and didn't see an easy solution outside of saving mouse state.

**Comment by JusKillmeQik** [comment]
Upon further reading and testing, I have been able to implement a test version that only steals focus when I destroy objects. If I hide them instead of destroying them, I should be able to leave focus on PoE. I'll keep this on the top of my list for the next release.

**Comment by JusKillmeQik** [comment]
Fixed: 2c88a87fa43da1495e3ce1136bb6372141624a0e
